import './globals.css'
import { StateContext } from './components/contextapi/useContext';
import { Toaster } from 'react-hot-toast'
import Header from './components/Header'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
              <StateContext>
      <Header/>

         <Toaster />
         {children}
               </StateContext>
               </body>
    </html>
  )
}
