import './globals.css'
import { StateContext } from './components/contextapi/useContext';

import Header from './components/Header'
import Footer from './components/Footer';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white'>
        <main className="  md:px-[9vw] px-[6vw] ">
              <StateContext>
          <Header/>

         {children}
         <Footer/>
               </StateContext>

               </main>
             
               </body>
    </html>
  )
}
